parameters:
    sonata.media.admin.media.class: Cube\CoreBundle\Admin\MediaAdmin

doctrine:
    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            timestampable: true
            sluggable: true
            sortable: true
            softdeleteable: true
            translatable: true

fos_user:
    db_driver:      orm
    firewall_name:  main
    user_class:     '%cube_core_entity_user%'
    group:
        group_class:   '%cube_core_entity_group%'
    from_email:
        address: "%mailer_user%"
        sender_name: Cube

sonata_admin:
    title: "CUBE"
    title_logo: bundles/cubecore/img/logo.png
    templates:
        layout: 'CubeCoreBundle:sonata:admin_layout.html.twig'
    show_mosaic_button: false
    dashboard:
        blocks:
        groups:
            sonata.admin.group.content:
                label: admin.dashboard.cms
                icon: '<i class="fa fa-th"></i>'
                label_catalogue: CubeCoreBundle
                items:
                    - sonata.media.admin.media
                    - sonata.media.admin.gallery
            sonata.admin.group.classification:
                label:           sonata_classification
                label_catalogue: SonataClassificationBundle
                icon:            '<i class="fa fa-sitemap"></i>'
                items:
                    - sonata.classification.admin.category
                    - sonata.classification.admin.tag
                    - sonata.classification.admin.context
            sonata.admin.group.administration:
                label: sonata_administration
                icon: '<i class="fa fa-cogs"></i>'
                label_catalogue: SonataAdminBundle
                items:
                    - sonata.user.admin.user
                    - sonata.user.admin.group

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_classification:
    class:
        tag:          '%cube_core_entity_tag%'
        category:     '%cube_core_entity_category%'
        collection:   Cube\CoreBundle\Entity\Collection
        context:      Cube\CoreBundle\Entity\Context
        media:        '%cube_core_entity_media%'
    admin:
        tag:
            class:        Sonata\ClassificationBundle\Admin\TagAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        category:
            class:        Cube\CoreBundle\Admin\CategoryAdmin
            controller:   SonataClassificationBundle:CategoryAdmin
            translation:  SonataClassificationBundle
        collection:
            class:        Sonata\ClassificationBundle\Admin\CollectionAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle
        context:
            class:        Cube\CoreBundle\Admin\ContextAdmin
            controller:   SonataAdminBundle:CRUD
            translation:  SonataClassificationBundle

sonata_media:
    class:
        media: '%cube_core_entity_media%'
        gallery: Cube\CoreBundle\Entity\Gallery
        gallery_has_media: Cube\CoreBundle\Entity\GalleryHasMedia
        category: '%cube_core_entity_category%'
    default_context: default
    db_driver: doctrine_orm
    contexts:
        sonata_collection:
            providers:
              - sonata.media.provider.image

            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}

        sonata_category:
            providers:
              - sonata.media.provider.image


            formats:
                preview: { width: 100, quality: 100}
                wide:    { width: 820, quality: 100}
        default:
            providers:
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
            formats:
                small: { width: 100, quality: 70 }
                big:   { width: 500, quality: 70 }
    cdn:
        server:
            path: /uploads/media
    filesystem:
        local:
            directory:  "%kernel.root_dir%/../web/uploads/media"
            create:     false

sonata_user:
    class:
        user: '%cube_core_entity_user%'
        group: '%cube_core_entity_group%'
    manager_type: orm

sonata_block:
    default_contexts: [cms]
