admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

user:
    resource: "@CubeCoreBundle/Controller/"
    type:     annotation
